import { Recipe, PantryItem, MealPlanDay } from './types';

export const INITIAL_TAGS: string[] = [
  'HIGH-PROTEIN',
  'QUICK < 30 MIN',
  'SEAFOOD',
  'GLUTEN-FREE',
  'VEGETARIAN',
  'COMFORT',
  'KID-FRIENDLY',
  'MEAL PREP',
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: 'rec-1',
    name: 'Lemon Herb Salmon Bowl',
    ingredients: '2 Salmon Fillets (6oz), 1 cup Quinoa (uncooked), 1 Lemon (zested & juiced), 2 tbsp Fresh Dill (chopped), 1 ripe Avocado (sliced), 2 cups Arugula, 1 tbsp Extra Virgin Olive Oil, 1/2 tsp Sea Salt & Black Pepper',
    instructions: '1. Cook quinoa according to package directions with a pinch of salt.\n2. Season salmon fillets with olive oil, lemon zest, minced fresh dill, sea salt, and freshly cracked black pepper.\n3. Heat a skillet over medium-high heat. Sear salmon for 4-5 minutes per side until skin is crisp and flesh is flaky and pink.\n4. Fluff quinoa and divide into shallow ceramic bowls over a bed of fresh arugula.\n5. Rest salmon on top, fan out fresh avocado slices, and finish with a bright squeeze of lemon juice.',
    cookTimeMins: 25,
    ratingAatish: 5,
    ratingFaeeza: 5,
    tags: ['HIGH-PROTEIN', 'QUICK < 30 MIN', 'SEAFOOD', 'GLUTEN-FREE'],
    notes: 'Family all-time favorite! Best with wild Alaskan sockeye salmon.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1000&auto=format&fit=crop&q=80',
    lastCookedDate: '2026-09-02',
    createdBy: 'Aatish',
    lastEditedBy: 'Faeeza',
    lastEditedTimestamp: '2026-09-10T14:20:00Z',
    calories: 480,
    servings: 2,
  },
  {
    id: 'rec-2',
    name: 'Greek Yogurt & Granola Bowl',
    ingredients: '2 cups Greek Yogurt (Plain or Vanilla), 1 cup Honey Almond Granola, 1/2 cup Fresh Blueberries, 1/2 cup Fresh Raspberries, 1 tbsp Chia Seeds, 2 tbsp Wildflower Honey',
    instructions: '1. Spoon rich Greek yogurt into serving bowls.\n2. Layer half the berries and crisp honey almond granola in the center.\n3. Top with remaining fresh raspberries, blueberries, and a sprinkle of chia seeds.\n4. Drizzle lightly with wildflower honey just before serving.',
    cookTimeMins: 10,
    ratingAatish: 4,
    ratingFaeeza: 5,
    tags: ['QUICK < 30 MIN', 'VEGETARIAN', 'HIGH-PROTEIN'],
    notes: 'Great quick breakfast or light weekend lunch.',
    imageUrl: 'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=1000&auto=format&fit=crop&q=80',
    lastCookedDate: '2026-09-11',
    createdBy: 'Faeeza',
    lastEditedBy: 'Faeeza',
    lastEditedTimestamp: '2026-09-11T08:15:00Z',
    calories: 340,
    servings: 2,
  },
  {
    id: 'rec-3',
    name: 'Roasted Veggie Grain Bowl',
    ingredients: '1 can Chickpeas (rinsed & drained), 1 Sweet Potato (diced), 1 cup Broccoli Florets, 1 Red Bell Pepper (sliced), 1 cup Farro or Brown Rice, 2 tbsp Tahini, 1 tbsp Maple Syrup, 1 tbsp Lemon Juice, 2 tbsp Olive Oil, 1 tsp Smoked Paprika',
    instructions: '1. Preheat oven to 400°F (200°C). Toss chickpeas and diced veggies in olive oil, paprika, salt, and pepper.\n2. Spread on baking sheet and roast for 25 minutes until caramelized and tender.\n3. Cook farro in vegetable broth for maximum flavor.\n4. Whisk tahini, maple syrup, lemon juice, and warm water for creamy dressing.\n5. Assemble grain base, arranged roasted veggies and crispy chickpeas, and drizzle dressing.',
    cookTimeMins: 30,
    ratingAatish: 4,
    ratingFaeeza: 5,
    tags: ['VEGETARIAN', 'HIGH-PROTEIN', 'COMFORT'],
    notes: 'Super filling and excellent for meal-prep leftovers.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=1000&auto=format&fit=crop&q=80',
    lastCookedDate: '2026-08-20',
    createdBy: 'Faeeza',
    lastEditedBy: 'Aatish',
    lastEditedTimestamp: '2026-09-01T19:30:00Z',
    calories: 420,
    servings: 2,
  },
  {
    id: 'rec-4',
    name: 'Spicy Morning Shakshuka',
    ingredients: '4 Large Eggs, 1 can (14oz) Crushed San Marzano Tomatoes, 1 Red Bell Pepper (diced), 1 Yellow Onion (diced), 2 cloves Garlic (minced), 1 tsp Ground Cumin, 1 tsp Smoked Paprika, 1/4 tsp Red Pepper Flakes, 1/4 cup Feta Cheese (crumbled), Fresh Cilantro or Parsley, Warm Sourdough Bread',
    instructions: '1. Sauté diced onion and red bell pepper in olive oil until soft and sweet.\n2. Add garlic, cumin, paprika, and red pepper flakes; stir until fragrant (1 minute).\n3. Pour in crushed tomatoes, simmer for 10 minutes until sauce thickens.\n4. Use a spoon to make 4 wells in the sauce. Crack an egg into each well.\n5. Cover skillet and cook gently for 5-8 minutes until egg whites set but yolks remain runny.\n6. Top with crumbled feta and fresh cilantro. Serve hot with toasted sourdough.',
    cookTimeMins: 20,
    ratingAatish: 5,
    ratingFaeeza: 4,
    tags: ['HIGH-PROTEIN', 'QUICK < 30 MIN', 'COMFORT', 'VEGETARIAN'],
    notes: 'Aatish loves extra chili flakes and crusty sourdough for dipping.',
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=1000&auto=format&fit=crop&q=80',
    lastCookedDate: '2026-08-25',
    createdBy: 'Aatish',
    lastEditedBy: 'Aatish',
    lastEditedTimestamp: '2026-09-05T10:00:00Z',
    calories: 390,
    servings: 2,
  },
  {
    id: 'rec-5',
    name: 'Lemon Garlic Shrimp Pasta',
    ingredients: '1 lb Raw Shrimp (peeled & deveined), 8 oz Linguine or Fettuccine, 4 cloves Garlic (thinly sliced), 1/4 cup Dry White Wine or Broth, 3 tbsp Grass-fed Butter, 2 tbsp Olive Oil, 1 Lemon (juiced), 1/4 cup Grated Parmesan, 2 tbsp Fresh Parsley, 1/2 cup Cherry Tomatoes (halved)',
    instructions: '1. Boil linguine in salted water until al dente; reserve 1/2 cup pasta cooking water.\n2. Heat olive oil and 1 tbsp butter in a large skillet. Sauté shrimp with salt and pepper for 2 mins per side; remove.\n3. In same skillet, cook sliced garlic and cherry tomatoes for 1 minute until fragrant.\n4. Add white wine and lemon juice, scraping up golden bits, and simmer 2 minutes.\n5. Whisk in remaining butter, cooked pasta, and splash of pasta water until sauce clings.\n6. Toss in cooked shrimp, parmesan, and fresh parsley.',
    cookTimeMins: 20,
    ratingAatish: 5,
    ratingFaeeza: 5,
    tags: ['QUICK < 30 MIN', 'SEAFOOD', 'COMFORT'],
    notes: 'Date night staple! Takes only 20 minutes start to finish.',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=1000&auto=format&fit=crop&q=80',
    lastCookedDate: '2026-09-08',
    createdBy: 'Aatish',
    lastEditedBy: 'Faeeza',
    lastEditedTimestamp: '2026-09-08T20:10:00Z',
    calories: 520,
    servings: 3,
  },
  {
    id: 'rec-6',
    name: 'Berry Smoothie Power Bowl',
    ingredients: '2 cups Frozen Mixed Berries, 1 Frozen Banana, 1/2 cup Almond Milk, 1 scoop Vanilla Plant Protein, 1 Banana (freshly sliced), 2 tbsp Coconut Flakes, 1 tbsp Hemp Hearts, 1/4 cup Fresh Raspberries & Blueberries',
    instructions: '1. Blend frozen berries, frozen banana, protein powder, and almond milk on high until thick and scoopable (like soft serve).\n2. Pour into chilled ceramic smoothie bowls.\n3. Artfully arrange sliced fresh bananas, fresh berries, toasted coconut flakes, and hemp hearts in neat rows across the surface.',
    cookTimeMins: 8,
    ratingAatish: 3,
    ratingFaeeza: 5,
    tags: ['QUICK < 30 MIN', 'VEGETARIAN'],
    notes: 'Faeeza loves this post-workout; quick and refreshing.',
    imageUrl: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=1000&auto=format&fit=crop&q=80',
    lastCookedDate: '2026-09-06',
    createdBy: 'Faeeza',
    lastEditedBy: 'Faeeza',
    lastEditedTimestamp: '2026-09-06T09:30:00Z',
    calories: 310,
    servings: 2,
  },
  {
    id: 'rec-7',
    name: 'Rosemary Garlic Ribeye Steak',
    ingredients: '2 Ribeye Steaks (10oz each), 3 sprigs Fresh Rosemary, 4 cloves Garlic (smashed), 3 tbsp Butter, 1 bunch Fresh Asparagus, 1 tbsp Olive Oil, Coarse Kosher Salt, Cracked Black Pepper',
    instructions: '1. Pat steaks completely dry; season generously with coarse kosher salt and black pepper. Let rest 20 mins.\n2. Heat cast iron skillet until smoking hot with a splash of high-heat oil.\n3. Sear steaks 3 minutes on the first side to develop deep mahogany crust.\n4. Flip, add butter, smashed garlic, and fresh rosemary sprigs to the skillet.\n5. Tilt pan and baste steaks continuously with aromatic foamy butter for 3-4 minutes.\n6. Rest steaks for 7 minutes on a board. Flash sauté asparagus in remaining pan drippings.',
    cookTimeMins: 25,
    ratingAatish: 5,
    ratingFaeeza: 4,
    tags: ['HIGH-PROTEIN', 'QUICK < 30 MIN', 'COMFORT'],
    notes: 'Aatish special! Always use cast iron skillet.',
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1000&auto=format&fit=crop&q=80',
    lastCookedDate: '2026-08-14',
    createdBy: 'Aatish',
    lastEditedBy: 'Aatish',
    lastEditedTimestamp: '2026-08-14T21:00:00Z',
    calories: 580,
    servings: 2,
  },
  {
    id: 'rec-8',
    name: 'Creamy Tuscan Garlic Chicken',
    ingredients: '2 Boneless Chicken Breasts (halved horizontally), 1/2 cup Sun-Dried Tomatoes (drained & sliced), 2 cups Baby Spinach, 1 cup Heavy Cream or Coconut Cream, 1/2 cup Chicken Bone Broth, 4 cloves Garlic (minced), 1/2 cup Fresh Grated Parmesan, 1 tsp Italian Herbs, 2 tbsp Olive Oil',
    instructions: '1. Season chicken cutlets with Italian herbs, salt, and pepper. Sear in olive oil over medium-high heat until golden brown and cooked through (4-5 mins per side); transfer to plate.\n2. In the same pan, sauté garlic and sun-dried tomatoes for 1-2 minutes.\n3. Add chicken broth and cream; bring to a gentle simmer.\n4. Stir in grated parmesan until melted into a silky sauce.\n5. Add fresh baby spinach and stir until wilted.\n6. Return chicken to the pan to simmer in sauce for 3 minutes.',
    cookTimeMins: 30,
    ratingAatish: 5,
    ratingFaeeza: 5,
    tags: ['HIGH-PROTEIN', 'COMFORT', 'QUICK < 30 MIN'],
    notes: 'Rich and savory! Delicious with steamed green beans or pasta.',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=1000&auto=format&fit=crop&q=80',
    lastCookedDate: '2026-08-18',
    createdBy: 'Faeeza',
    lastEditedBy: 'Faeeza',
    lastEditedTimestamp: '2026-08-18T19:45:00Z',
    calories: 540,
    servings: 3,
  },
  {
    id: 'rec-9',
    name: 'Thai Coconut Green Curry with Tofu',
    ingredients: '1 block Extra-Firm Tofu (pressed & cubed), 1 can (14oz) Full-Fat Coconut Milk, 3 tbsp Thai Green Curry Paste, 1 cup Zucchini (sliced), 1 cup Sugar Snap Peas, 1 Red Bell Pepper (sliced), 1 tbsp Fish Sauce or Tamari, 1 tbsp Brown Sugar, Fresh Thai Basil leaves, 2 cups Jasmine Rice',
    instructions: '1. Pan-fry cubed tofu in a tablespoon of oil until golden and crisp; set aside.\n2. Heat 2 tbsp of the thick coconut cream from top of can in a pot; fry curry paste for 2 minutes until aromatic.\n3. Pour in remaining coconut milk and 1/2 cup water or broth. Bring to a gentle simmer.\n4. Add zucchini, bell pepper, and snap peas; simmer 5-7 minutes until tender-crisp.\n5. Season with fish sauce/tamari and brown sugar. Fold in crispy tofu.\n6. Remove from heat and stir in fresh Thai basil. Serve over steaming jasmine rice.',
    cookTimeMins: 25,
    ratingAatish: 4,
    ratingFaeeza: 5,
    tags: ['VEGETARIAN', 'QUICK < 30 MIN'],
    notes: 'Fragrant and comforting on chilly evenings.',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=1000&auto=format&fit=crop&q=80',
    lastCookedDate: '2026-08-05',
    createdBy: 'Faeeza',
    lastEditedBy: 'Aatish',
    lastEditedTimestamp: '2026-08-05T19:00:00Z',
    calories: 410,
    servings: 3,
  },
  {
    id: 'rec-10',
    name: 'Crispy Baked Fish Tacos',
    ingredients: '1 lb Cod or Halibut fillets (cut into strips), 8 Small Corn Tortillas, 2 cups Shredded Purple Cabbage, 1/4 cup Mayonnaise, 2 tbsp Lime Juice, 1 tsp Chipotle Chili Powder, 1 ripe Avocado (diced), 1/4 cup Fresh Cilantro, Lime wedges',
    instructions: '1. Preheat oven to 425°F (220°C). Season fish strips with chipotle powder, cumin, and salt. Bake for 12-14 minutes until flaky.\n2. Whisk mayo, lime juice, and a pinch of salt to create chipotle lime crema.\n3. Toss purple cabbage with half the crema for a crunchy slaw.\n4. Warm corn tortillas on a dry skillet until charred.\n5. Assemble tacos: charred tortilla, crunchy slaw, crispy baked fish, diced avocado, and fresh cilantro.',
    cookTimeMins: 25,
    ratingAatish: 5,
    ratingFaeeza: 4,
    tags: ['QUICK < 30 MIN', 'SEAFOOD', 'HIGH-PROTEIN'],
    notes: 'Taco Tuesday regular! Add hot sauce for extra kick.',
    imageUrl: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=1000&auto=format&fit=crop&q=80',
    lastCookedDate: '2026-08-10',
    createdBy: 'Aatish',
    lastEditedBy: 'Aatish',
    lastEditedTimestamp: '2026-08-10T19:30:00Z',
    calories: 440,
    servings: 3,
  },
];

export const INITIAL_PANTRY: PantryItem[] = [
  { id: 'pan-1', itemName: 'Salmon Fillets', category: 'Meat & Seafood', inStock: true, useFirst: true, addedDate: '11-09', expiry: '15-09' },
  { id: 'pan-2', itemName: 'Quinoa', category: 'Pantry Staples', inStock: true, useFirst: false, addedDate: '01-09', expiry: '30-12' },
  { id: 'pan-3', itemName: 'Extra Virgin Olive Oil', category: 'Pantry Staples', inStock: true, useFirst: false, addedDate: '28-08', expiry: '15-11' },
  { id: 'pan-4', itemName: 'Lemons', category: 'Fruit&Veg', inStock: true, useFirst: false, addedDate: '10-09', expiry: '22-09' },
  { id: 'pan-5', itemName: 'Fresh Dill', category: 'Fruit&Veg', inStock: true, useFirst: true, addedDate: '12-09', expiry: '16-09' },
  { id: 'pan-6', itemName: 'Avocados', category: 'Fruit&Veg', inStock: true, useFirst: true, addedDate: '12-09', expiry: '16-09' },
  { id: 'pan-7', itemName: 'Greek Yogurt', category: 'Dairy & Eggs', inStock: true, useFirst: false, addedDate: '10-09', expiry: '24-09' },
  { id: 'pan-8', itemName: 'Large Eggs', category: 'Dairy & Eggs', inStock: true, useFirst: false, addedDate: '08-09', expiry: '28-09' },
  { id: 'pan-9', itemName: 'Crushed Tomatoes', category: 'Pantry Staples', inStock: true, useFirst: false, addedDate: '15-08', expiry: '10-12' },
  { id: 'pan-10', itemName: 'Feta Cheese', category: 'Dairy & Eggs', inStock: true, useFirst: false, addedDate: '05-09', expiry: '25-09' },
  { id: 'pan-11', itemName: 'Shrimp', category: 'Meat & Seafood', inStock: false, useFirst: false, addedDate: '13-09' },
  { id: 'pan-12', itemName: 'Linguine Pasta', category: 'Pantry Staples', inStock: true, useFirst: false, addedDate: '02-09', expiry: '15-01' },
  { id: 'pan-13', itemName: 'Parmesan Cheese', category: 'Dairy & Eggs', inStock: true, useFirst: false, addedDate: '04-09', expiry: '30-10' },
  { id: 'pan-14', itemName: 'Ribeye Steaks', category: 'Meat & Seafood', inStock: false, useFirst: false, addedDate: '13-09' },
  { id: 'pan-15', itemName: 'Fresh Rosemary', category: 'Fruit&Veg', inStock: false, useFirst: false, addedDate: '13-09' },
  { id: 'pan-16', itemName: 'Asparagus', category: 'Fruit&Veg', inStock: false, useFirst: false, addedDate: '13-09' },
  { id: 'pan-17', itemName: 'Chicken Breasts', category: 'Meat & Seafood', inStock: true, useFirst: false, addedDate: '12-09', expiry: '16-09' },
  { id: 'pan-18', itemName: 'Sun-Dried Tomatoes', category: 'Pantry Staples', inStock: true, useFirst: false, addedDate: '20-08', expiry: '20-11' },
  { id: 'pan-19', itemName: 'Baby Spinach', category: 'Fruit&Veg', inStock: false, useFirst: false, addedDate: '13-09' },
  { id: 'pan-20', itemName: 'Heavy Cream', category: 'Dairy & Eggs', inStock: false, useFirst: false, addedDate: '13-09' },
  { id: 'pan-21', itemName: 'Frozen Mixed Berries', category: 'Frozen', inStock: true, useFirst: false, addedDate: '01-09', expiry: '15-12' },
  { id: 'pan-22', itemName: 'Chia Seeds', category: 'Pantry Staples', inStock: true, useFirst: false, addedDate: '15-08', expiry: '01-02' },
  { id: 'pan-23', itemName: 'Parchment Paper', category: 'General', inStock: true, useFirst: false, addedDate: '10-09' },
];

export const INITIAL_MEAL_PLAN: MealPlanDay[] = [
  {
    dayOfWeek: 'Mon',
    dayName: 'Monday',
    date: '2026-09-14',
    breakfastRecipeId: 'rec-2',
    breakfastRecipeName: 'Greek Yogurt & Granola Bowl',
    breakfastAssignedTo: 'Faeeza',
    lunchRecipeId: undefined,
    lunchRecipeName: undefined,
    lunchAssignedTo: undefined,
    recipeId: 'rec-1',
    recipeName: 'Lemon Herb Salmon Bowl',
    assignedTo: 'Aatish',
    isLeftoverOrOut: false,
    leftoverType: 'none',
    isLocked: true,
    notes: 'Uses dill & avocados from pantry (Use First).',
  },
  {
    dayOfWeek: 'Tue',
    dayName: 'Tuesday',
    date: '2026-09-15',
    breakfastRecipeId: undefined,
    breakfastRecipeName: undefined,
    breakfastAssignedTo: undefined,
    lunchRecipeId: undefined,
    lunchRecipeName: undefined,
    lunchAssignedTo: undefined,
    recipeId: 'rec-4',
    recipeName: 'Spicy Morning Shakshuka',
    assignedTo: 'Faeeza',
    isLeftoverOrOut: false,
    leftoverType: 'none',
    isLocked: false,
    notes: 'Quick 20 min dinner with warm bread.',
  },
  {
    dayOfWeek: 'Wed',
    dayName: 'Wednesday',
    date: '2026-09-16',
    breakfastRecipeId: 'rec-6',
    breakfastRecipeName: 'Berry Smoothie Power Bowl',
    breakfastAssignedTo: 'Faeeza',
    lunchRecipeId: 'rec-3',
    lunchRecipeName: 'Roasted Veggie Grain Bowl',
    lunchAssignedTo: 'Aatish',
    recipeId: 'rec-5',
    recipeName: 'Lemon Garlic Shrimp Pasta',
    assignedTo: 'Together',
    isLeftoverOrOut: false,
    leftoverType: 'none',
    isLocked: false,
    notes: 'Mid-week pasta celebration!',
  },
  {
    dayOfWeek: 'Thu',
    dayName: 'Thursday',
    date: '2026-09-17',
    breakfastRecipeId: undefined,
    breakfastRecipeName: undefined,
    breakfastAssignedTo: undefined,
    lunchRecipeId: undefined,
    lunchRecipeName: undefined,
    lunchAssignedTo: undefined,
    recipeId: 'rec-8',
    recipeName: 'Creamy Tuscan Garlic Chicken',
    assignedTo: 'Aatish',
    isLeftoverOrOut: false,
    leftoverType: 'none',
    isLocked: false,
    notes: 'Comforting rich chicken skillet.',
  },
  {
    dayOfWeek: 'Fri',
    dayName: 'Friday',
    date: '2026-09-18',
    breakfastRecipeId: undefined,
    breakfastRecipeName: undefined,
    breakfastAssignedTo: undefined,
    lunchRecipeId: undefined,
    lunchRecipeName: undefined,
    lunchAssignedTo: undefined,
    recipeId: 'rec-10',
    recipeName: 'Crispy Baked Fish Tacos',
    assignedTo: 'Faeeza',
    isLeftoverOrOut: false,
    leftoverType: 'none',
    isLocked: false,
    notes: 'Friday taco night!',
  },
  {
    dayOfWeek: 'Sat',
    dayName: 'Saturday',
    date: '2026-09-19',
    breakfastRecipeId: 'rec-4',
    breakfastRecipeName: 'Spicy Morning Shakshuka',
    breakfastAssignedTo: 'Aatish',
    lunchRecipeId: undefined,
    lunchRecipeName: undefined,
    lunchAssignedTo: undefined,
    recipeId: 'rec-7',
    recipeName: 'Rosemary Garlic Ribeye Steak',
    assignedTo: 'Aatish',
    isLeftoverOrOut: false,
    leftoverType: 'none',
    isLocked: true,
    notes: 'Saturday steak night with fresh asparagus.',
  },
  {
    dayOfWeek: 'Sun',
    dayName: 'Sunday',
    date: '2026-09-20',
    breakfastRecipeId: undefined,
    breakfastRecipeName: undefined,
    breakfastAssignedTo: undefined,
    lunchRecipeId: undefined,
    lunchRecipeName: undefined,
    lunchAssignedTo: undefined,
    recipeId: 'rec-3',
    recipeName: 'Roasted Veggie Grain Bowl',
    assignedTo: 'Together',
    isLeftoverOrOut: false,
    leftoverType: 'none',
    isLocked: false,
    notes: 'Healthy reset & meal prep for the upcoming week.',
  },
];
